name: Generate Readme Doc
on:
  workflow_dispatch:
  push:
    paths:
      - '*.json'
      - 'readme.html'
    branches-ignore:
      - '^(HEAD detached at'
      - next
      - main
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
     - uses: 'phantomcyber/dev-cicd-tools/github-actions/generate-doc@main'
       with:
         GITHUB_TOKEN: ${{ secrets.SOAR_APPS_TOKEN }}
